// lib/prompts.js
//
// Catálogo de prompts por modo, compartido entre api/generarFoto.js y
// api/consultarFoto.js. Vivir fuera de /api evita que Vercel lo trate como
// una ruta propia.

const DOMINIO_BASE = 'https://wide.nexoled.cl';

const PROMPTS_POR_MODO = {
  game_of_thrones:
    "Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo. Extreme close-up POV selfie, camera held very close to the face(s) — the figure(s) fill the left third of frame from the shoulders up, face bathed in soft, cinematic light, looking directly into the camera — fair or pale skin, delicate features, neutral yet warmly confident expression. They wear dark, heavy medieval robes with luxurious fur trim along the collar and cuffs, layered beneath a hooded cloak that drapes naturally, textured and worn with elegant, faded embroidery. Gender-neutral, androgynous features suggest non-binary presence — smooth, balanced, without overt gender cues. Filling the right two-thirds of the frame at extremely close range, a colossal dragon head looms in massive scale — ancient and unblinking, also looking directly into the camera alongside them — one glowing amber eye pulses gently at close range, radiating mystical energy, filling a large portion of the frame. Its scales shimmer with moisture, dark and intricately textured, smoke curling richly from its nostrils just behind the figure's shoulder. Behind them, softly out of focus, the silhouette of the Iron Throne — jagged shapes of countless fused swords catching flickers of torchlight — barely legible in the shallow depth of field, hinting at the seat of power without pulling focus from the close subjects. Warm orange torchlight glows against cold dark stone and iron. No armor, no weapons — just powerful, unguarded presence. Cinematic, photorealistic, hyper-detailed, Game of Thrones-inspired atmosphere — extreme close-up framing, shallow depth of field, emphasizing intimacy and scale.",

  peaky_style:
    "Use the face(s) from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. Photorealistic human skin texture, no plastic/doll/3D-render look. Medium-shot composition (waist-up or wider), realistic anatomical proportions (head 1/7-1/8 of body height). Dark navy or black three-piece suit, long black wool overcoat, flat cap (newsboy style) worn low, waistcoat with visible pocket watch and chain, slicked back hair with undercut, muted moody color palette (dark navy, black, charcoal — no brown tweed tones). Background: gritty 1920s Birmingham cobblestone street with brick buildings, overcast desaturated lighting, cinematic haze. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  breaking_bad:
    "Use the face(s) from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. Photorealistic human skin, no plastic/doll/3D-render look. Medium-shot composition (waist-up or wider), realistic anatomical proportions (head 1/7-1/8 of body height). Bright yellow chemical hazmat suit, hood down, face fully visible. Gas mask held in one hand at side, empty object only — no face/eyes/reflection inside the lens. Background: rundown desert RV mobile lab, blue-tinted chemical glassware, desert light through windows. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  viejitos:
    "Use the face(s) from the reference photo as the identity source — preserve core facial identity and recognizability. Photorealistic skin texture with realistic aging. Medium-shot composition (waist-up or wider), realistic anatomical proportions (head 1/7-1/8 of body height). Age each person to approximately 60-70 years old: white/gray hair, deep wrinkles, age spots, looser skin texture. Keep clothing style and lighting consistent with original. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo. No cartoon effect.",

  harry_magic:
    "Use the face(s) from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. Photorealistic human skin, no plastic/doll/3D-render look. Medium-shot composition (waist-up or wider), realistic anatomical proportions (head 1/7-1/8 of body height). Black school robe with house-colored tie and trim, holding a wand. Background: great hall of a magic school, floating candles, stone archways, warm magical lighting. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  super_hero:
    "Use the face from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. The generated body must have completely photorealistic human skin texture and tone matching the reference face — no plastic, doll-like, toy, or 3D-render appearance anywhere on the body, hands, or neck. Generate a medium-shot composition (waist-up or wider) with realistic, anatomically correct human proportions — the head-to-body ratio must match a normal adult (head roughly 1/7th to 1/8th of total body height, not oversized). Outfit: for a feminine look, a warrior-style superheroine — sleeveless red and gold bustier-style top, blue star-patterned bottom, gold tiara-style headband, gold wrist cuffs, confident powerful stance. For a masculine look, a blue-and-silver super-soldier suit with a star emblem on the chest, round shield nearby. Background: dramatic city skyline at dusk with energy/light effects, cinematic superhero movie lighting. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  grease:
    "Use the face(s) from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. Photorealistic human skin, no plastic/doll/3D-render look. Medium-shot composition (waist-up or wider), realistic anatomical proportions (head 1/7-1/8 of body height). Masculine: black leather jacket, white t-shirt, slicked hair. Feminine: strapless black off-shoulder top, voluminous curly tousled hair, smoky eye makeup, red lipstick. Background: retro diner or drive-in at dusk, neon signs, classic cars. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  jurassic_park:
    "Use the face(s) from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. Photorealistic human skin, no plastic/doll/3D-render look. Medium-shot composition (waist-up or wider), realistic anatomical proportions (head 1/7-1/8 of body height). Khaki safari-style outfit: tan vest or shirt, wide-brim hat optional. Background: dense jungle with a large realistic dinosaur visible, misty adventure lighting. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  simpsons:
    "Keep the person's face, hands, body proportions, and body size 100% identical to the original reference photo — do not enlarge, stretch, or resize the real person's body or head in any way, regardless of the size of the surrounding cartoon characters. Keep the same number of people as in the original photo. Place them sitting on a solid brown leather-style couch (classic Simpsons living room sofa), yellow-toned living room walls, a small framed painting of a sailboat on the wall behind them. Include the full Simpsons family rendered as 3D Pixar-style cartoon characters with yellow skin (not flat 2D) sitting and standing naturally around them on the same couch, sized appropriately to fit the scene without altering the real person: Homer and Marge (tall blue beehive hair) standing behind the couch, Bart sitting on the couch, Lisa sitting on the couch playing her saxophone with both hands, and Maggie — same yellow Simpsons skin tone, tiny infant proportions, single blue hair tuft, blue onesie, pacifier in mouth, sitting on the floor in front of the couch. The real human person(s) must remain fully photorealistic, unchanged, and at their original body proportions.",

  princesa_disney:
    "Use the face(s) from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. Photorealistic human skin, no plastic/doll/3D-render look. Medium-shot composition (waist-up or wider), realistic anatomical proportions (head 1/7-1/8 of body height). Feminine: elegant pastel ballgown, delicate tiara, romantic hairstyle. Masculine: royal prince-style jacket with gold trim, epaulettes. Background: castle ballroom or enchanted garden at golden hour, sparkling light particles. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  disco_70s:
    "Use the face from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. The generated body must have completely photorealistic human skin texture and tone matching the reference face — no plastic, doll-like, toy, or 3D-render appearance anywhere on the body, hands, or neck. Generate a new half-body composition with realistic, anatomically correct human proportions — the head-to-body ratio must match a normal adult (head is roughly 1/7th to 1/8th of total body height, not oversized). Outfit: 1970s disco style — for a feminine look, a shimmering sequined or metallic wrap top/dress in gold, silver, or jewel tones, glossy voluminous hair. For a masculine look, an open-collar satin shirt with gold chain, flared trousers. Background: retro 1970s disco club interior, mirror ball overhead, colorful dance floor light tiles, vibrant neon lighting. Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  barbie:
    "Use the face from the reference photo as the identity source — preserve exact facial features, skin tone, and likeness. The generated body must have completely photorealistic human skin texture and tone matching the reference face — no plastic, doll-like, toy, or 3D-render appearance anywhere on the body, hands, or neck. Generate a medium-shot composition (waist-up or wider) with realistic, anatomically correct human proportions — the head-to-body ratio must match a normal adult (head roughly 1/7th to 1/8th of total body height, not oversized). Outfit: for a feminine look, a bright pink glamorous top or dress with glossy styled hair, confident pose. For a masculine look, Ken-style fitted white or pastel polo shirt, styled hair, confident pose. Background: pink plastic-looking dream house interior with visible furniture and decor, or a pink convertible car with palm trees, bold pink and pastel color palette, glossy toy-like lighting on the environment only (not on the person's skin). Keep the exact same people of reference, all of them must appear in the result, each one keeping THEIR OWN individual facial identity from the reference photo.",

  futbol_fan_1: {
    prompt:
      "This is a two-reference composition. Reference Photo A is the main subject(s) — if Photo A shows two people, BOTH must appear unchanged in the result, each clearly recognizable by face; keep the same framing and distance as a normal casual selfie (not extreme close-up, not overly zoomed). Reference Photo B is a professional football player — use his build, hairstyle, and generic athletic appearance from Photo B, noticeably taller than the people in Photo A (at least a head taller), athletic build, wearing a plain Netherland national soccer team jersey. The player stands slightly behind and between the person/people from Photo A, leaning in for the selfie, relaxed genuine smile, looking at camera. Background: subtle stadium atmosphere — softly blurred floodlights and crowd tones, not a sharp wide view of the field. Raw casual phone-selfie look, natural skin texture, soft ambient lighting, not overly cinematic or staged.",
    refFija: 'futbol1.jpg',
  },
  futbol_fan_2: {
    prompt:
      "This is a two-reference composition. Reference Photo A is the main subject(s) — if Photo A shows two people, BOTH must appear unchanged in the result, each clearly recognizable by face; keep the same framing and distance as a normal casual selfie (not extreme close-up, not overly zoomed). Reference Photo B is a professional football player — use his build, hairstyle, and generic athletic appearance from Photo B, noticeably taller than the people in Photo A (at least a half a head taller), athletic build, wearing a France national soccer team jersey. The player stands slightly behind and between the person/people from Photo A, leaning in for the selfie, relaxed genuine smile, looking at camera. Background: subtle stadium atmosphere — softly blurred floodlights and crowd tones, not a sharp wide view of the field. Raw casual phone-selfie look, natural skin texture, soft ambient lighting, not overly cinematic or staged.",
    refFija: 'futbol2.jpg',
  },
  futbol_fan_3: {
    prompt:
      "This is a two-reference composition. Reference Photo A is the main subject(s) — if Photo A shows two people, BOTH must appear unchanged in the result, each clearly recognizable by face; keep the same framing and distance as a normal casual selfie (not extreme close-up, not overly zoomed). Reference Photo B is a professional football player — use his build, hairstyle, and athletic appearance from Photo B, noticeably taller than the people in Photo A (at least a head taller), athletic build, wearing a Portugal national soccer team jersey. The player stands slightly behind and between the person/people from Photo A, leaning in for the selfie, relaxed genuine smile, looking at camera. Background: subtle stadium atmosphere — softly blurred floodlights and crowd tones, not a sharp wide view of the field. Raw casual phone-selfie look, natural skin texture, soft ambient lighting, not overly cinematic or staged.",
    refFija: 'futbol3.jpg',
  },
  futbol_fan_4: {
    prompt:
      "This is a two-reference composition. Reference Photo A is the main subject(s) — if Photo A shows two people, BOTH must appear unchanged in the result, each clearly recognizable by face; keep the same framing and distance as a normal casual selfie (not extreme close-up, not overly zoomed). Reference Photo B is a professional football player — he is 1.70 meters tall, adjust to composition, athletic build, wearing an Argentinian national selection jersey. The player stands slightly behind and between the person/people from Photo A, leaning in for the selfie, relaxed genuine smile, looking at camera. Background: subtle stadium atmosphere — softly blurred floodlights and crowd tones, not a sharp wide view of the field. Raw casual phone-selfie look, natural skin texture, soft ambient lighting, not overly cinematic or staged.",
    refFija: 'futbol4.jpg',
  },
};

module.exports = { PROMPTS_POR_MODO, DOMINIO_BASE };